[bar.default]
background_opacity = 0.60999998636543751
capsule = true
capsule_opacity = 0.69999998435378075
capsule_thickness = 0.5599999912083149
center = [ "workspaces", "spacer_1", "clock", "spacer_1" ]
end = [ "media", "spacer_1", "tray", "notifications", "network", "volume", "bluetooth", "battery", "session" ]
margin_edge = 8
margin_ends = 24
radius = 24
radius_bottom_left = 10
radius_bottom_right = 10
radius_top_left = 10
radius_top_right = 10
start = [ "launcher", "spacer_1", "group:g1", "active_window" ]

[dock]
active_monitor_only = true
auto_hide = true
background_opacity = 0.63999998569488525
enabled = true
icon_size = 38
pinned = [
    "chrome-lnachpgegbbmnnlgpokibfjlmppeciah-Default",
    "sublime_text",
    "com.anthropic.Claude",
    "slack",
    "todoist",
    "google-chrome",
    "org.telegram.desktop",
    "com.ktechpit.whatsie",
    "qbz",
    "chrome-kadndpdhfiaigidpmcgmgabmbcjnjbgn-Default"
]
reserve_space = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 70.0
    box_width = 400.0
    cx = 1920.0
    cy = 2041.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 720.0
    cy = 781.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[shell.screen_corners]
enabled = true
size = 34

[theme]
wallpaper_scheme = "m3-fruit-salad"

[wallpaper.default]
path = "/home/eddie/Pictures/Wallpapers/Sun-Setting-Horizon.png"

[wallpaper.last]
path = "/home/eddie/Pictures/Wallpapers/Sun-Setting-Horizon.png"

[wallpaper.monitors.eDP-1]
path = "/home/eddie/Pictures/Wallpapers/Sun-Setting-Horizon.png"

[widget.clock]
anchor = true
font_weight = 700
format = "{:%H:%M %A}"

[widget.launcher]
glyph = "rocket"

[widget.tray]
hidden = [ "whatsie", "todoist", "telegram-desktop" ]

[widget.workspaces]
display = "id"
hide_when_empty = true